#!/usr/bin/env python3

from discord.ext import commands
import os

from modules import db

from modules.connections import database_file as database_file
from modules.connections import bot_token as bot_token

if not os.path.exists(database_file):
    db.query("CREATE TABLE config (setting, parent, value, flag)")
    db.query("CREATE TABLE admins (user_id, permissions)")

    db.query("CREATE TABLE rssfeed_tracklist (url)")
    db.query("CREATE TABLE rssfeed_channels (url, channel_id)")
    db.query("CREATE TABLE rssfeed_history (url, entry_id)")

    db.query("CREATE TABLE rankfeed_channel_list (channel_id)")
    db.query("CREATE TABLE rankfeed_history (mapset_id)")

    db.query("CREATE TABLE usereventfeed_tracklist (osu_id)")
    db.query("CREATE TABLE usereventfeed_channels (osu_id, channel_id)")
    db.query("CREATE TABLE usereventfeed_history (osu_id, event_id, timestamp)")

    db.query("CREATE TABLE groupfeed_channel_list (channel_id)")
    db.query("CREATE TABLE groupfeed_members (osu_id, username, group_id)")
    db.query("CREATE TABLE groupfeed_json_data (group_id, contents)")

initial_extensions = [
    "cogs.BotManagement",
    "cogs.GroupFeed",
    "cogs.RankFeed",
    "cogs.RSSFeed",
    "cogs.UserEventFeed",
]


class Youmu(commands.Bot):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.background_tasks = []
        self.app_version = (open(".version", "r+").read()).rstrip()
        self.description = f"Youmu {self.app_version}"

        for extension in initial_extensions:
            try:
                self.load_extension(extension)
            except Exception as e:
                print(e)

    async def close(self):
        # Cancel all Task object generated by cogs.
        # This prevents any task still running due to having long sleep time.
        for task in self.background_tasks:
            task.cancel()
        
        # Run actual discord.py close.
        await super().close()

    async def on_ready(self):
        print("Logged in as")
        print(self.user.name)
        print(self.user.id)
        print("------")
        if not db.query("SELECT * FROM admins"):
            app_info = await self.application_info()
            if app_info.team:
                for team_member in app_info.team.members:
                    db.query(["INSERT INTO admins VALUES (?, ?)", [str(team_member.id), "1"]])
                    print(f"Added {team_member.name} to admin list")
            else:
                db.query(["INSERT INTO admins VALUES (?, ?)", [str(app_info.owner.id), "1"]])
                print(f"Added {app_info.owner.name} to admin list")


client = Youmu(command_prefix=".")
client.run(bot_token)
